### ISSUE TITLE
Doesn't work on Windows 10 ? 

### ISSUE THREAD

**Issue by acezard** [timoxley/npm-run#10]
Hi, it seems npm-run doesn't work on my windows. Basically it will return a `not found: module-xyz` for every module I tried. But on bash on ubuntu for windows, same machine, it works (and in both cases, nothing is globally installed). Is it as intended ? Thank you

**Comment by timoxley** [comment]
@acezard sorry about the delay, I've updated a bunch of dependencies for `npm-run@4.1.1` and some of those relate to windows compatibility. Can you please try again?

**Comment by kbrandwijk** [comment]
I just tried this on Windows 10 and it works very well!

**Comment by timoxley** [comment]
Thanks for the feedback. 

Feel free to reopen this ticket if problem is not resolved.
