### ISSUE TITLE
Upvote the answer on the StackOverflow question

### ISSUE THREAD

**Issue by mightyiam** [timoxley/npm-run#11]
http://stackoverflow.com/a/40313363/359072

And maybe put this in the readme so that future users will upvote.

**Comment by timoxley** [comment]
I'm not going to put it in the readme, seems like upvote harvesting, but I appreciate you pointing it out 👍

**Comment by mightyiam** [comment]
It *is* upvote harvesting. For the purpose of bringing the most efficient solution upwards to be the most visible answer.

**Comment by timoxley** [comment]
Linking to it from the project doesn't seem morally right to me.

**Comment by mightyiam** [comment]
I can get that. The current situation is that there are five worst answers that have a higher score. I would care more for the discoverability of the best answer than the unwritten rules of stackoverflow. Top moral priority the way I see it is to save the next developers their precious time.

Not arguing. Do as you please.
