### ISSUE TITLE
Node Security Advisory violation

### ISSUE THREAD

**Issue by doug-wade** [timoxley/npm-run#16]
My build is failing with security violation errors due to npm-run's dependency on [syncExec](https://github.com/gvarsanyi/sync-exec), as [reported in this issue](https://github.com/gvarsanyi/sync-exec/issues/17) and detailed in [node security advisory 310](https://nodesecurity.io/advisories/310).  We should remove the polyfill, as child.execSync has been [supported since 0.11.12](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options), which has been end-of-life since [2016-10-31](https://github.com/nodejs/Release).

**Comment by timoxley** [comment]
On my phone at the moment but will look at this later today
